packages:
  - '.'

nodeLinker: hoisted
blockExoticSubdeps: false
onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - koffi
  - '@electron/node-gyp'
allowBuilds:
  electron-winstaller: true
  koffi: true
