import { app, BrowserWindow, screen, globalShortcut, ipcMain } from 'electron';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
let SHAppBarMessage: any = null;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let APPBARDATA: any = null;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let koffi: any = null;

const MY_APPBAR_MSG_ID = 1124;

let mainWindow: BrowserWindow | null = null;
let spotlightWindow: BrowserWindow | null = null;

if (process.platform === 'win32') {
  try {
    koffi = require('koffi');

    const RECT = koffi.struct('RECT', {
      left: 'int32',
      top: 'int32',
      right: 'int32',
      bottom: 'int32'
    });

    APPBARDATA = koffi.struct('APPBARDATA', {
      cbSize: 'uint32',
      hWnd: 'void*',
      uCallbackMessage: 'uint32',
      uEdge: 'uint32',
      rc: RECT,
      lParam: 'intptr_t'
    });

    const shell32 = koffi.load('shell32.dll');
    SHAppBarMessage = shell32.func('uintptr_t SHAppBarMessage(uint32_t dwMessage, _Inout_ APPBARDATA *pData)');
  } catch (err) {
    console.error('Failed to initialize Windows AppBar API:', err);
  }
}

const registerAppBar = (hwnd: Buffer, win: BrowserWindow) => {
  if (!SHAppBarMessage || !APPBARDATA) return;

  const data = {
    cbSize: koffi.sizeof(APPBARDATA),
    hWnd: hwnd,
    uCallbackMessage: MY_APPBAR_MSG_ID,
    uEdge: 2, // ABE_RIGHT = 2
    rc: { left: 0, top: 0, right: 0, bottom: 0 },
    lParam: 0
  };

  SHAppBarMessage(0, data); // ABM_NEW = 0

  // Hook window message for position changes
  win.hookWindowMessage(MY_APPBAR_MSG_ID, (wParam: Buffer) => {
    const code = wParam.length === 8 ? wParam.readBigUInt64LE(0) : BigInt(wParam.readUInt32LE(0));
    if (code === BigInt(1)) { // ABN_POSCHANGED = 1
      updateAppBarPosition(hwnd, win);
    }
  });

  // Perform initial positioning
  updateAppBarPosition(hwnd, win);
};

const updateAppBarPosition = (hwnd: Buffer, win: BrowserWindow) => {
  if (!SHAppBarMessage || !APPBARDATA) return;

  const primaryDisplay = screen.getPrimaryDisplay();
  const { x, y, width, height } = primaryDisplay.bounds;
  const dockWidth = 400;

  const data = {
    cbSize: koffi.sizeof(APPBARDATA),
    hWnd: hwnd,
    uCallbackMessage: MY_APPBAR_MSG_ID,
    uEdge: 2, // ABE_RIGHT = 2
    rc: {
      left: x + width - dockWidth,
      top: y,
      right: x + width,
      bottom: y + height
    },
    lParam: 0
  };

  SHAppBarMessage(2, data); // ABM_QUERYPOS = 2
  SHAppBarMessage(3, data); // ABM_SETPOS = 3

  win.setBounds({
    x: data.rc.left,
    y: data.rc.top,
    width: data.rc.right - data.rc.left,
    height: data.rc.bottom - data.rc.top
  });
};

const unregisterAppBar = (hwnd: Buffer) => {
  if (!SHAppBarMessage || !APPBARDATA) return;

  const data = {
    cbSize: koffi.sizeof(APPBARDATA),
    hWnd: hwnd,
    uCallbackMessage: 0,
    uEdge: 2,
    rc: { left: 0, top: 0, right: 0, bottom: 0 },
    lParam: 0
  };

  SHAppBarMessage(1, data); // ABM_REMOVE = 1
};

const createSpotlightWindow = (): void => {
  if (spotlightWindow) return;

  spotlightWindow = new BrowserWindow({
    width: 500,
    height: 70,
    frame: false,
    transparent: true,
    alwaysOnTop: true,
    show: false,
    resizable: false,
    skipTaskbar: true,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  spotlightWindow.loadURL(`${MAIN_WINDOW_WEBPACK_ENTRY}?window=spotlight`);

  spotlightWindow.on('blur', () => {
    if (spotlightWindow) {
      spotlightWindow.hide();
    }
  });

  spotlightWindow.on('closed', () => {
    spotlightWindow = null;
  });
};

const toggleSpotlightWindow = (): void => {
  if (!spotlightWindow) {
    createSpotlightWindow();
  }

  if (spotlightWindow) {
    if (spotlightWindow.isVisible()) {
      spotlightWindow.hide();
    } else {
      spotlightWindow.show();
      spotlightWindow.center();
      spotlightWindow.focus();
      spotlightWindow.webContents.send('spotlight-shown');
    }
  }
};

// IPC Handlers
ipcMain.on('submit-task', (event, text) => {
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send('task-added', text);
  }
  if (spotlightWindow) {
    spotlightWindow.hide();
  }
});

ipcMain.on('hide-spotlight', () => {
  if (spotlightWindow) {
    spotlightWindow.hide();
  }
});

ipcMain.on('toggle-always-on-top', () => {
  if (mainWindow && !mainWindow.isDestroyed()) {
    const state = !mainWindow.isAlwaysOnTop();
    mainWindow.setAlwaysOnTop(state);
    mainWindow.webContents.send('always-on-top-changed', state);
  }
});

ipcMain.handle('get-always-on-top', () => {
  if (mainWindow && !mainWindow.isDestroyed()) {
    return mainWindow.isAlwaysOnTop();
  }
  return false;
});

const createWindow = (): void => {
  const dockWidth = 400;

  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 600,
    width: dockWidth,
    frame: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  //mainWindow.webContents.openDevTools();

  const hwnd = mainWindow.getNativeWindowHandle();

  if (process.platform === 'win32' && SHAppBarMessage) {
    registerAppBar(hwnd, mainWindow);

    mainWindow.on('closed', () => {
      unregisterAppBar(hwnd);
      mainWindow = null;
    });
  } else {
    // Non-Windows platform: Position it on the right side of the monitor using the workArea
    const primaryDisplay = screen.getPrimaryDisplay();
    const { x, y, width: workAreaWidth, height: workAreaHeight } = primaryDisplay.workArea;
    mainWindow.setBounds({
      x: x + workAreaWidth - dockWidth,
      y: y,
      width: dockWidth,
      height: workAreaHeight
    });

    mainWindow.on('closed', () => {
      mainWindow = null;
    });
  }
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  createWindow();
  createSpotlightWindow();

  const shortcut = process.platform === 'win32' ? 'Ctrl+Space' : 'Option+Space';
  const registered = globalShortcut.register(shortcut, () => {
    toggleSpotlightWindow();
  });
  if (!registered) {
    console.log(`Registration failed for ${shortcut}, trying fallback Ctrl+Shift+Space`);
    globalShortcut.register('Ctrl+Shift+Space', () => {
      toggleSpotlightWindow();
    });
  }
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('will-quit', () => {
  globalShortcut.unregisterAll();
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
