import { app, BrowserWindow, screen, globalShortcut, ipcMain, dialog } from 'electron';
import {
  loadAutocompleteConfig,
  openAutocompleteConfigFile,
  startWatchingAutocompleteConfig,
  broadcastAutocompleteUpdate,
  stopWatchingAutocompleteConfig
} from './autocomplete';
import {
  loadConfig,
  openConfigFile,
  startWatchingConfig,
  stopWatchingConfig,
  formatHotkeyForDisplay,
  DEFAULT_CONFIG
} from './config';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
let SHAppBarMessage: any = null;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let APPBARDATA: any = null;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let koffi: any = null;

const MY_APPBAR_MSG_ID = 1124;

const ABM_NEW = 0;
const ABM_REMOVE = 1;
const ABM_QUERYPOS = 2;
const ABM_SETPOS = 3;

const ABE_LEFT = 0;
const ABE_RIGHT = 2;

const ABN_POSCHANGED = 1;

let mainWindow: BrowserWindow | null = null;
let spotlightWindow: BrowserWindow | null = null;
let isAppBarRegistered = false;
let currentDockSide: 'left' | 'right' | null = null;
let activeHotkey: string | null = null;

interface RECTType {
  left: number;
  top: number;
  right: number;
  bottom: number;
}

if (process.platform === 'win32') {
  try {
    koffi = require('koffi');

    const RECT = koffi.struct('RECT', {
      left: 'int32',
      top: 'int32',
      right: 'int32',
      bottom: 'int32'
    });

    APPBARDATA = koffi.struct('APPBARDATA', {
      cbSize: 'uint32',
      hWnd: 'intptr_t',
      uCallbackMessage: 'uint32',
      uEdge: 'uint32',
      rc: RECT,
      lParam: 'intptr_t'
    });

    const shell32 = koffi.load('shell32.dll');
    SHAppBarMessage = shell32.func('uintptr_t __stdcall SHAppBarMessage(uint32_t dwMessage, _Inout_ APPBARDATA *pData)');
  } catch (err) {
    console.error('Failed to initialize Windows AppBar API:', err);
  }
}

const getWindowHwnd = (win: BrowserWindow): bigint => {
  const buf = win.getNativeWindowHandle();
  return process.arch === 'ia32' ? BigInt(buf.readUInt32LE(0)) : buf.readBigUInt64LE(0);
};

const callAppBar = (
  dwMessage: number,
  hwndBigInt: bigint,
  uEdge: number,
  rc?: RECTType
): { res: number; rc: RECTType; uEdge: number } => {
  if (!SHAppBarMessage || !APPBARDATA || !koffi) {
    return { res: 0, rc: rc || { left: 0, top: 0, right: 0, bottom: 0 }, uEdge };
  }

  const pData = koffi.alloc(APPBARDATA, 1);
  koffi.encode(pData, APPBARDATA, {
    cbSize: koffi.sizeof(APPBARDATA),
    hWnd: hwndBigInt,
    uCallbackMessage: MY_APPBAR_MSG_ID,
    uEdge: uEdge,
    rc: rc || { left: 0, top: 0, right: 0, bottom: 0 },
    lParam: 0
  });

  const res = SHAppBarMessage(dwMessage, pData);
  const decoded = koffi.decode(pData, APPBARDATA);
  return { res: Number(res), rc: decoded.rc, uEdge: decoded.uEdge };
};

const dockWindow = (side: 'left' | 'right') => {
  if (!mainWindow || mainWindow.isDestroyed()) return;

  const uEdge = side === 'left' ? ABE_LEFT : ABE_RIGHT;
  const currentBounds = mainWindow.getBounds();
  const display = screen.getDisplayMatching(currentBounds);
  const scale = display.scaleFactor || 1;
  const dockWidth = 400;

  if (process.platform === 'win32' && SHAppBarMessage) {
    const hwnd = getWindowHwnd(mainWindow);

    // If not registered yet, register as an AppBar
    if (!isAppBarRegistered) {
      callAppBar(ABM_NEW, hwnd, uEdge);
      isAppBarRegistered = true;
    }

    // Convert display bounds to physical pixels for Win32 API
    const monLeftPhysical = Math.round(display.bounds.x * scale);
    const monTopPhysical = Math.round(display.bounds.y * scale);
    const monRightPhysical = Math.round((display.bounds.x + display.bounds.width) * scale);
    const monBottomPhysical = Math.round((display.bounds.y + display.bounds.height) * scale);
    const dockWidthPhysical = Math.round(dockWidth * scale);

    const initialRc: RECTType = {
      left: side === 'left' ? monLeftPhysical : monRightPhysical - dockWidthPhysical,
      top: monTopPhysical,
      right: side === 'left' ? monLeftPhysical + dockWidthPhysical : monRightPhysical,
      bottom: monBottomPhysical
    };

    // ABM_QUERYPOS: request position
    const queryResult = callAppBar(ABM_QUERYPOS, hwnd, uEdge, initialRc);

    // Maintain requested width on the chosen edge
    const adjustedRc: RECTType = { ...queryResult.rc };
    if (uEdge === ABE_LEFT) {
      adjustedRc.right = adjustedRc.left + dockWidthPhysical;
    } else {
      adjustedRc.left = adjustedRc.right - dockWidthPhysical;
    }

    // ABM_SETPOS: reserve space in the OS desktop work area
    const setPosResult = callAppBar(ABM_SETPOS, hwnd, uEdge, adjustedRc);

    // Convert result back from physical pixels to DIPs for Electron
    const finalBounds = {
      x: Math.round(setPosResult.rc.left / scale),
      y: Math.round(setPosResult.rc.top / scale),
      width: Math.round((setPosResult.rc.right - setPosResult.rc.left) / scale),
      height: Math.round((setPosResult.rc.bottom - setPosResult.rc.top) / scale)
    };

    mainWindow.setBounds(finalBounds);
    currentDockSide = side;
  } else {
    // Non-Windows fallback
    const { x, y, width: workAreaWidth, height: workAreaHeight } = display.workArea;
    mainWindow.setBounds({
      x: side === 'left' ? x : x + workAreaWidth - dockWidth,
      y: y,
      width: dockWidth,
      height: workAreaHeight
    });
    currentDockSide = side;
  }

  if (!mainWindow.isAlwaysOnTop()) {
    mainWindow.setAlwaysOnTop(true);
    mainWindow.webContents.send('always-on-top-changed', true);
  }
};

const floatWindow = () => {
  if (!mainWindow || mainWindow.isDestroyed()) return;

  if (process.platform === 'win32' && SHAppBarMessage && isAppBarRegistered) {
    const hwnd = getWindowHwnd(mainWindow);
    const uEdge = currentDockSide === 'left' ? ABE_LEFT : ABE_RIGHT;
    callAppBar(ABM_REMOVE, hwnd, uEdge);
    isAppBarRegistered = false;
  }

  currentDockSide = null;

  const currentBounds = mainWindow.getBounds();
  const display = screen.getDisplayMatching(currentBounds);
  const { x, y, width, height } = display.workArea;
  const defaultWidth = 400;
  const defaultHeight = 600;

  mainWindow.setBounds({
    x: Math.round(x + (width - defaultWidth) / 2),
    y: Math.round(y + (height - defaultHeight) / 2),
    width: defaultWidth,
    height: defaultHeight
  });
};

const cleanupAppBar = () => {
  if (mainWindow && !mainWindow.isDestroyed() && process.platform === 'win32' && SHAppBarMessage && isAppBarRegistered) {
    try {
      const hwnd = getWindowHwnd(mainWindow);
      const uEdge = currentDockSide === 'left' ? ABE_LEFT : ABE_RIGHT;
      callAppBar(ABM_REMOVE, hwnd, uEdge);
    } catch (err) {
      console.error('Failed to unregister AppBar on exit:', err);
    }
    isAppBarRegistered = false;
    currentDockSide = null;
  }
};

const createSpotlightWindow = (): void => {
  if (spotlightWindow) return;

  spotlightWindow = new BrowserWindow({
    width: 500,
    height: 72,
    frame: false,
    transparent: false,
    alwaysOnTop: true,
    show: false,
    resizable: false,
    skipTaskbar: true,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  spotlightWindow.loadURL(`${MAIN_WINDOW_WEBPACK_ENTRY}?window=spotlight`);

  spotlightWindow.on('blur', () => {
    if (spotlightWindow) {
      spotlightWindow.hide();
    }
  });

  spotlightWindow.on('closed', () => {
    spotlightWindow = null;
  });
};

const toggleSpotlightWindow = (): void => {
  if (!spotlightWindow) {
    createSpotlightWindow();
  }

  if (spotlightWindow) {
    if (spotlightWindow.isVisible()) {
      spotlightWindow.hide();
    } else {
      spotlightWindow.show();
      spotlightWindow.center();
      spotlightWindow.focus();
      spotlightWindow.webContents.send('spotlight-shown');
    }
  }
};

// IPC Handlers
ipcMain.on('submit-task', (event, text) => {
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send('task-added', text);
  }
  if (spotlightWindow) {
    spotlightWindow.hide();
  }
});

ipcMain.on('hide-spotlight', () => {
  if (spotlightWindow) {
    spotlightWindow.hide();
  }
});

ipcMain.on('quit-app', () => {
  app.quit();
});

ipcMain.on('dock-window', (event, side: 'left' | 'right') => {
  dockWindow(side);
});

ipcMain.on('float-window', () => {
  floatWindow();
});

ipcMain.on('toggle-always-on-top', () => {
  if (mainWindow && !mainWindow.isDestroyed()) {
    const state = !mainWindow.isAlwaysOnTop();
    mainWindow.setAlwaysOnTop(state);
    mainWindow.webContents.send('always-on-top-changed', state);
  }
});

ipcMain.handle('get-always-on-top', () => {
  if (mainWindow && !mainWindow.isDestroyed()) {
    return mainWindow.isAlwaysOnTop();
  }
  return false;
});

ipcMain.handle('get-autocomplete-data', () => {
  return loadAutocompleteConfig();
});

ipcMain.handle('open-autocomplete-config', async () => {
  await openAutocompleteConfigFile();
});

ipcMain.handle('get-config', () => {
  return loadConfig();
});

ipcMain.handle('open-config', async () => {
  await openConfigFile();
});

ipcMain.handle('get-hotkey-string', () => {
  return formatHotkeyForDisplay(activeHotkey || loadConfig().globalHotkey || DEFAULT_CONFIG.globalHotkey);
});

const registerGlobalHotkey = (accelerator: string): boolean => {
  try {
    return globalShortcut.register(accelerator, () => {
      toggleSpotlightWindow();
    });
  } catch (err) {
    console.error(`Error registering hotkey "${accelerator}":`, err);
    return false;
  }
};

const createWindow = (): void => {
  const dockWidth = 400;
  const defaultHeight = 600;

  const primaryDisplay = screen.getPrimaryDisplay();
  const { x, y, width, height } = primaryDisplay.workArea;

  // Create the browser window in floating mode by default
  mainWindow = new BrowserWindow({
    x: Math.round(x + (width - dockWidth) / 2),
    y: Math.round(y + (height - defaultHeight) / 2),
    height: defaultHeight,
    width: dockWidth,
    minWidth: 320,
    frame: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Hook window message for position changes from Windows AppBar notifications
  if (process.platform === 'win32' && SHAppBarMessage) {
    mainWindow.hookWindowMessage(MY_APPBAR_MSG_ID, (wParam: Buffer) => {
      const code = wParam.length === 8 ? wParam.readBigUInt64LE(0) : BigInt(wParam.readUInt32LE(0));
      if (code === BigInt(ABN_POSCHANGED)) {
        if (isAppBarRegistered && currentDockSide) {
          dockWindow(currentDockSide);
        }
      }
    });
  }

  mainWindow.on('close', () => {
    cleanupAppBar();
  });

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  createWindow();
  createSpotlightWindow();

  startWatchingAutocompleteConfig(() => {
    broadcastAutocompleteUpdate([mainWindow, spotlightWindow]);
  });

  const config = loadConfig();
  const targetHotkey = config.globalHotkey || DEFAULT_CONFIG.globalHotkey;
  if (registerGlobalHotkey(targetHotkey)) {
    activeHotkey = targetHotkey;
  } else {
    console.error(`Failed to register global hotkey "${targetHotkey}"`);
    dialog.showErrorBox(
      'Global Hotkey Error',
      `Failed to register global hotkey "${targetHotkey}".\n\nIt may be invalid or already in use by another application.`
    );
  }

  startWatchingConfig((newConfig) => {
    const newHotkey = newConfig.globalHotkey || DEFAULT_CONFIG.globalHotkey;
    if (newHotkey !== activeHotkey) {
      if (mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send('hotkey-config-changed', {
          newHotkey,
          activeHotkey: activeHotkey || ''
        });
      }
    }
  });
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('will-quit', () => {
  stopWatchingAutocompleteConfig();
  stopWatchingConfig();
  cleanupAppBar();
  globalShortcut.unregisterAll();
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
