import { app, BrowserWindow, screen, nativeImage, nativeTheme } from 'electron';
import * as path from 'path';
import * as fs from 'fs';
import { sendAlwaysOnTopChanged, sendSpotlightShown } from './ipc';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

export type DockSide = 'left' | 'right';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
let SHAppBarMessage: any = null;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let APPBARDATA: any = null;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let koffi: any = null;

const MY_APPBAR_MSG_ID = 1124;

const ABM_NEW = 0;
const ABM_REMOVE = 1;
const ABM_QUERYPOS = 2;
const ABM_SETPOS = 3;

const ABE_LEFT = 0;
const ABE_RIGHT = 2;

const ABN_POSCHANGED = 1;

interface RECTType {
  left: number;
  top: number;
  right: number;
  bottom: number;
}

let mainWindow: BrowserWindow | null = null;
let spotlightWindow: BrowserWindow | null = null;
let isAppBarRegistered = false;
let currentDockSide: DockSide | null = null;

export const initAppBarApi = (): boolean => {
  if (process.platform !== 'win32') return false;
  if (SHAppBarMessage && APPBARDATA && koffi) return true;

  try {
    koffi = require('koffi');

    const RECT = koffi.struct('RECT', {
      left: 'int32',
      top: 'int32',
      right: 'int32',
      bottom: 'int32'
    });

    APPBARDATA = koffi.struct('APPBARDATA', {
      cbSize: 'uint32',
      hWnd: 'intptr_t',
      uCallbackMessage: 'uint32',
      uEdge: 'uint32',
      rc: RECT,
      lParam: 'intptr_t'
    });

    const shell32 = koffi.load('shell32.dll');
    SHAppBarMessage = shell32.func('uintptr_t __stdcall SHAppBarMessage(uint32_t dwMessage, _Inout_ APPBARDATA *pData)');
    return true;
  } catch (err) {
    console.error('Failed to initialize Windows AppBar API:', err);
    return false;
  }
};

const getWindowHwnd = (win: BrowserWindow): bigint => {
  const buf = win.getNativeWindowHandle();
  return process.arch === 'ia32' ? BigInt(buf.readUInt32LE(0)) : buf.readBigUInt64LE(0);
};

const callAppBar = (
  dwMessage: number,
  hwndBigInt: bigint,
  uEdge: number,
  rc?: RECTType
): { res: number; rc: RECTType; uEdge: number } => {
  if (!SHAppBarMessage || !APPBARDATA || !koffi) {
    return { res: 0, rc: rc || { left: 0, top: 0, right: 0, bottom: 0 }, uEdge };
  }

  const pData = koffi.alloc(APPBARDATA, 1);
  koffi.encode(pData, APPBARDATA, {
    cbSize: koffi.sizeof(APPBARDATA),
    hWnd: hwndBigInt,
    uCallbackMessage: MY_APPBAR_MSG_ID,
    uEdge: uEdge,
    rc: rc || { left: 0, top: 0, right: 0, bottom: 0 },
    lParam: 0
  });

  const res = SHAppBarMessage(dwMessage, pData);
  const decoded = koffi.decode(pData, APPBARDATA);
  return { res: Number(res), rc: decoded.rc, uEdge: decoded.uEdge };
};

export const getAppIcon = (): Electron.NativeImage => {
  const iconFileName = process.platform === 'darwin' ? 'icon.icns' : 'icon.ico';
  const candidatePaths = [
    path.join(process.resourcesPath, 'assets', iconFileName),
    path.join(app.getAppPath(), 'assets', iconFileName),
    path.join(__dirname, '../../assets', iconFileName),
    // Fallback to alternative format if preferred platform format isn't found
    path.join(process.resourcesPath, 'assets', process.platform === 'darwin' ? 'icon.ico' : 'icon.icns'),
    path.join(app.getAppPath(), 'assets', process.platform === 'darwin' ? 'icon.ico' : 'icon.icns'),
    path.join(__dirname, '../../assets', process.platform === 'darwin' ? 'icon.ico' : 'icon.icns'),
  ];

  for (const candidate of candidatePaths) {
    if (fs.existsSync(candidate)) {
      const img = nativeImage.createFromPath(candidate);
      if (!img.isEmpty()) {
        return img;
      }
    }
  }

  return nativeImage.createEmpty();
};

export const getMainWindow = (): BrowserWindow | null => mainWindow;
export const getSpotlightWindow = (): BrowserWindow | null => spotlightWindow;
export const getAppWindows = (): Array<BrowserWindow | null | undefined> => [mainWindow, spotlightWindow];
export const getCurrentDockSide = (): DockSide | null => currentDockSide;
export const isWindowAppBarRegistered = (): boolean => isAppBarRegistered;

export const restoreMainWindow = (): void => {
  if (mainWindow && !mainWindow.isDestroyed()) {
    if (mainWindow.isMinimized()) {
      mainWindow.restore();
    }
    if (!mainWindow.isVisible()) {
      mainWindow.show();
    }
    mainWindow.focus();
  }
};

export const dockMainWindow = (side: DockSide): void => {
  if (!mainWindow || mainWindow.isDestroyed()) return;

  const uEdge = side === 'left' ? ABE_LEFT : ABE_RIGHT;
  const currentBounds = mainWindow.getBounds();
  const display = screen.getDisplayMatching(currentBounds);
  const scale = display.scaleFactor || 1;
  const dockWidth = 400;

  if (process.platform === 'win32' && SHAppBarMessage) {
    const hwnd = getWindowHwnd(mainWindow);

    // If not registered yet, register as an AppBar
    if (!isAppBarRegistered) {
      callAppBar(ABM_NEW, hwnd, uEdge);
      isAppBarRegistered = true;
    }

    // Convert display bounds to physical pixels for Win32 API
    const monLeftPhysical = Math.round(display.bounds.x * scale);
    const monTopPhysical = Math.round(display.bounds.y * scale);
    const monRightPhysical = Math.round((display.bounds.x + display.bounds.width) * scale);
    const monBottomPhysical = Math.round((display.bounds.y + display.bounds.height) * scale);
    const dockWidthPhysical = Math.round(dockWidth * scale);

    const initialRc: RECTType = {
      left: side === 'left' ? monLeftPhysical : monRightPhysical - dockWidthPhysical,
      top: monTopPhysical,
      right: side === 'left' ? monLeftPhysical + dockWidthPhysical : monRightPhysical,
      bottom: monBottomPhysical
    };

    // ABM_QUERYPOS: request position
    const queryResult = callAppBar(ABM_QUERYPOS, hwnd, uEdge, initialRc);

    // Maintain requested width on the chosen edge
    const adjustedRc: RECTType = { ...queryResult.rc };
    if (uEdge === ABE_LEFT) {
      adjustedRc.right = adjustedRc.left + dockWidthPhysical;
    } else {
      adjustedRc.left = adjustedRc.right - dockWidthPhysical;
    }

    // ABM_SETPOS: reserve space in the OS desktop work area
    const setPosResult = callAppBar(ABM_SETPOS, hwnd, uEdge, adjustedRc);

    // Convert result back from physical pixels to DIPs for Electron
    const finalBounds = {
      x: Math.round(setPosResult.rc.left / scale),
      y: Math.round(setPosResult.rc.top / scale),
      width: Math.round((setPosResult.rc.right - setPosResult.rc.left) / scale),
      height: Math.round((setPosResult.rc.bottom - setPosResult.rc.top) / scale)
    };

    mainWindow.setBounds(finalBounds);
    currentDockSide = side;
  } else {
    // Non-Windows fallback
    const { x, y, width: workAreaWidth, height: workAreaHeight } = display.workArea;
    mainWindow.setBounds({
      x: side === 'left' ? x : x + workAreaWidth - dockWidth,
      y: y,
      width: dockWidth,
      height: workAreaHeight
    });
    currentDockSide = side;
  }

  if (!mainWindow.isAlwaysOnTop()) {
    mainWindow.setAlwaysOnTop(true);
    sendAlwaysOnTopChanged(mainWindow, true);
  }
};

export const floatMainWindow = (): void => {
  if (!mainWindow || mainWindow.isDestroyed()) return;

  if (process.platform === 'win32' && SHAppBarMessage && isAppBarRegistered) {
    const hwnd = getWindowHwnd(mainWindow);
    const uEdge = currentDockSide === 'left' ? ABE_LEFT : ABE_RIGHT;
    callAppBar(ABM_REMOVE, hwnd, uEdge);
    isAppBarRegistered = false;
  }

  currentDockSide = null;

  const currentBounds = mainWindow.getBounds();
  const display = screen.getDisplayMatching(currentBounds);
  const { x, y, width, height } = display.workArea;
  const defaultWidth = 400;
  const defaultHeight = 600;

  mainWindow.setBounds({
    x: Math.round(x + (width - defaultWidth) / 2),
    y: Math.round(y + (height - defaultHeight) / 2),
    width: defaultWidth,
    height: defaultHeight
  });

  if (mainWindow.isAlwaysOnTop()) {
    mainWindow.setAlwaysOnTop(false);
    sendAlwaysOnTopChanged(mainWindow, false);
  }
};

export const cleanupAppBar = (): void => {
  if (
    mainWindow &&
    !mainWindow.isDestroyed() &&
    process.platform === 'win32' &&
    SHAppBarMessage &&
    isAppBarRegistered
  ) {
    try {
      const hwnd = getWindowHwnd(mainWindow);
      const uEdge = currentDockSide === 'left' ? ABE_LEFT : ABE_RIGHT;
      callAppBar(ABM_REMOVE, hwnd, uEdge);
    } catch (err) {
      console.error('Failed to unregister AppBar on exit:', err);
    }
    isAppBarRegistered = false;
    currentDockSide = null;
  }
};

export const createMainWindow = (): BrowserWindow => {
  initAppBarApi();

  const dockWidth = 400;
  const defaultHeight = 600;

  const primaryDisplay = screen.getPrimaryDisplay();
  const { x, y, width, height } = primaryDisplay.workArea;

  const appIcon = getAppIcon();

  // Create the browser window in floating mode by default
  mainWindow = new BrowserWindow({
    title: 'TaskConveyor',
    x: Math.round(x + (width - dockWidth) / 2),
    y: Math.round(y + (height - defaultHeight) / 2),
    height: defaultHeight,
    width: dockWidth,
    minWidth: 320,
    frame: false,
    skipTaskbar: true,
    icon: appIcon.isEmpty() ? undefined : appIcon,
    backgroundColor: nativeTheme.shouldUseDarkColors ? '#141618' : '#f8f9fa',
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Hook window message for position changes from Windows AppBar notifications
  if (process.platform === 'win32' && SHAppBarMessage) {
    mainWindow.hookWindowMessage(MY_APPBAR_MSG_ID, (wParam: Buffer) => {
      const code = wParam.length === 8 ? wParam.readBigUInt64LE(0) : BigInt(wParam.readUInt32LE(0));
      if (code === BigInt(ABN_POSCHANGED)) {
        if (isAppBarRegistered && currentDockSide) {
          dockMainWindow(currentDockSide);
        }
      }
    });
  }

  mainWindow.on('close', () => {
    cleanupAppBar();
  });

  mainWindow.on('closed', () => {
    mainWindow = null;
  });

  return mainWindow;
};

export const createSpotlightWindow = (): BrowserWindow => {
  if (spotlightWindow) return spotlightWindow;

  const appIcon = getAppIcon();

  spotlightWindow = new BrowserWindow({
    title: 'TaskConveyor',
    width: 500,
    height: 72,
    frame: false,
    transparent: false,
    alwaysOnTop: true,
    show: false,
    resizable: false,
    skipTaskbar: true,
    icon: appIcon.isEmpty() ? undefined : appIcon,
    backgroundColor: nativeTheme.shouldUseDarkColors ? '#1e2124' : '#ffffff',
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  spotlightWindow.loadURL(`${MAIN_WINDOW_WEBPACK_ENTRY}?window=spotlight`);

  spotlightWindow.on('blur', () => {
    if (spotlightWindow) {
      spotlightWindow.hide();
    }
  });

  spotlightWindow.on('closed', () => {
    spotlightWindow = null;
  });

  return spotlightWindow;
};

export const toggleSpotlightWindow = (): void => {
  if (!spotlightWindow || spotlightWindow.isDestroyed()) {
    createSpotlightWindow();
  }

  if (spotlightWindow && !spotlightWindow.isDestroyed()) {
    if (spotlightWindow.isVisible()) {
      spotlightWindow.hide();
    } else {
      spotlightWindow.show();
      spotlightWindow.center();
      spotlightWindow.focus();
      sendSpotlightShown(spotlightWindow);
    }
  }
};
